recreate release-source
datavisyn/github-workflows pull request #61
Opened 2024-04-04 12:35 UTC by dv-hossam-radwan

2024-04-22 06:32 UTC, dvvanessastoiber requested changes

2024-04-22 06:32 UTC, dvvanessastoiber commented on .github/workflows/release-source.yml
> +          release_version="$(jq -r '.version' package.json | cut -d '-' -f 1)"
Thank you for the changes! If I see it correctly, you are currently just removing the `-SNAPSHOT` and using that version as release version. But what if we need a major or minor release? We need to handle this as well.

2024-04-24 12:17 UTC, dv-hossam-radwan commented on .github/workflows/release-source.yml
> +          release_version="$(jq -r '.version' package.json | cut -d '-' -f 1)"
Changes added

2024-05-07 11:46 UTC, dvvanessastoiber requested changes
Thank you very much for the implementation! I have a few more comments, but it looks great already! Thank you also for incorporating the special cases for helm chart repos!

2024-05-07 11:46 UTC, dvvanessastoiber commented on .github/workflows/release-source.yml
> +            echo "Valind input"
```suggestion
            echo "Valid input"
```

2024-05-07 11:46 UTC, dvvanessastoiber commented on .github/workflows/release-source.yml
> +            echo "Error: invaled input version."
```suggestion
            echo "Error: invalid input version."
```

2024-05-07 11:46 UTC, dvvanessastoiber commented on .github/workflows/release-source.yml
> +          git checkout -b release/"$RELEASE_VERSION"
```suggestion
          git checkout -b release-"$RELEASE_VERSION"
```
Please avoid `/` in branch names - they sometimes cause issues in GA

2024-05-07 11:46 UTC, dvvanessastoiber commented on .github/workflows/release-source.yml
> +          helm-docs .
```suggestion
          helm-docs --document-dependency-values
```

2024-05-07 11:50 UTC, dvvanessastoiber commented on .github/workflows/release-source.yml
> +          # commit and push changes
please remember to add a helm dep update and helm dep build as the last step before running the helm-docs command

2024-05-08 12:22 UTC, dv-hossam-radwan commented on .github/workflows/release-source.yml
> +            echo "Valind input"
Changes addes

2024-05-08 12:22 UTC, dv-hossam-radwan commented on .github/workflows/release-source.yml
> +            echo "Error: invaled input version."
changes added

2024-05-08 12:22 UTC, dv-hossam-radwan commented on .github/workflows/release-source.yml
> +          git checkout -b release/"$RELEASE_VERSION"
changes added

2024-05-08 12:23 UTC, dv-hossam-radwan commented on .github/workflows/release-source.yml
> +          # commit and push changes
changes added

2024-05-08 12:23 UTC, dv-hossam-radwan commented
Sample output after changes:
https://github.com/datavisyn/test-app/actions/runs/9001672000/job/24728373045.
https://github.com/datavisyn/test-app/pull/57

2024-08-08 09:50 UTC, dvvanessastoiber commented
closed in favor of https://github.com/datavisyn/github-workflows/pull/74

2024-08-08 09:50 UTC, closed without merging